# 머신러닝 실습 : 고객 구매 데이터로 성별 예측 모델링 (분류 문제)
주어진 데이터는 백화점 고객의 1년 간 구매 데이터입니다. 
고객 3,500명에 대한 학습용 데이터(y.csv, X.csv)를 이용하여 성별예측 모형을 만들어보세요. 
모델의 성능은 자유롭게 측정해봅니다!

## 0. 라이브러리 불러오기

In [80]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings(action='ignore')

## 1. 데이터 불러오기

In [157]:
X = pd.read_csv('./data/X.csv', encoding='euc-kr')
y = pd.read_csv('./data/y.csv', encoding='euc-kr')

In [158]:

X.head()

,cust_id,총구매액,최대구매액,환불금액,주구매상품,주구매지점,내점일수,내점당구매건수,주말방문비율,구매주기
0,0,68282840,11264000,6860000.0,기타,강남점,19,3.894737,0.527027,17
1,1,2136000,2136000,300000.0,스포츠,잠실점,2,1.500000,0.000000,1
2,2,3197000,1639000,NaN,남성 캐주얼,관악점,2,2.000000,0.000000,1
3,3,16077620,4935000,NaN,기타,광주점,18,2.444444,0.318182,16
4,4,29050000,24000000,NaN,보석,본 점,2,1.500000,0.000000,85

In [159]:

y.head()

   cust_id  gender
0        0       0
1        1       0
2        2       1
3        3       1
4        4       0

In [160]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cust_id  3500 non-null   int64
 1   총구매액     3500 non-null   int64
 2   최대구매액    3500 non-null   int64
 3   환불금액     1205 non-null   float64
 4   주구매상품    3500 non-null   str
 5   주구매지점    3500 non-null   str
 6   내점일수     3500 non-null   int64
 7   내점당구매건수  3500 non-null   float64
 8   주말방문비율   3500 non-null   float64
 9   구매주기     3500 non-null   int64
dtypes: float64(3), int64(5), str(2)
memory usage: 273.6 KB

In [161]:
print("X의 cust_id 중복 개수:", X['cust_id'].duplicated().sum())
print("y의 cust_id 중복 개수:", y['cust_id'].duplicated().sum())

X의 cust_id 중복 개수: 0
y의 cust_id 중복 개수: 0

In [162]:
y['gender'].value_counts() #0 여성, 1 남성

gender
0    2184
1    1316
Name: count, dtype: int64

In [163]:
y["gender"].value_counts(normalize=True, dropna=False).sort_index() * 100

gender
0    62.4
1    37.6
Name: proportion, dtype: float64

해석
- 완전한 균형은 아니지만 심한 불균형도 아님
- 6:4 비율 수준 → 일반적인 이진분류 문제에서 허용 가능한 수준
- 현재 단계에서는 class_weight 없이 기본 모델로 먼저 학습 진행
- 이후 성능이 한쪽 클래스에 치우치면 class_weight='balanced' 적용 고려

In [164]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cust_id  3500 non-null   int64
 1   총구매액     3500 non-null   int64
 2   최대구매액    3500 non-null   int64
 3   환불금액     1205 non-null   float64
 4   주구매상품    3500 non-null   str
 5   주구매지점    3500 non-null   str
 6   내점일수     3500 non-null   int64
 7   내점당구매건수  3500 non-null   float64
 8   주말방문비율   3500 non-null   float64
 9   구매주기     3500 non-null   int64
dtypes: float64(3), int64(5), str(2)
memory usage: 273.6 KB

In [165]:
X.describe()

,cust_id,총구매액,최대구매액,환불금액,내점일수,내점당구매건수,주말방문비율,구매주기
count,3500.000000,3.500000e+03,3.500000e+03,1.205000e+03,3500.000000,3500.000000,3500.000000,3500.000000
mean,1749.500000,9.191925e+07,1.966424e+07,2.407822e+07,19.253714,2.834963,0.307246,20.958286
std,1010.507298,1.635065e+08,3.199235e+07,4.746453e+07,27.174942,1.912368,0.289752,24.748682
min,0.000000,-5.242152e+07,-2.992000e+06,5.600000e+03,1.000000,1.000000,0.000000,0.000000
25%,874.750000,4.747050e+06,2.875000e+06,2.259000e+06,2.000000,1.666667,0.027291,4.000000
50%,1749.500000,2.822270e+07,9.837000e+06,7.392000e+06,8.000000,2.333333,0.256410,13.000000
75%,2624.250000,1.065079e+08,2.296250e+07,2.412000e+07,25.000000,3.375000,0.448980,28.000000
max,3499.000000,2.323180e+09,7.066290e+08,5.637530e+08,285.000000,22.083333,1.000000,166.000000

In [166]:
# X에서 cust_id 제거
X = X.drop(columns=["cust_id"])

# y에서 cust_id 제거(타깃만 남김)
y = y["gender"]

In [168]:
missing_count = X.isna().sum().sort_values(ascending=False)
missing_count

총구매액       0
최대구매액      0
환불금액       0
주구매상품      0
주구매지점      0
내점일수       0
내점당구매건수    0
주말방문비율     0
구매주기       0
dtype: int64

In [167]:
X = X.fillna(0)

In [169]:
cat_cols = X.select_dtypes(include=['object'])
col_list = cat_cols.columns.to_list() #chaining
col_list

['주구매상품', '주구매지점']

In [170]:
for col in col_list:
  # print(col)
  print(X[col].nunique())
  print(X[col].value_counts().head()) #범주형변수의 값의 종류

42
주구매상품
기타      595
가공식품    546
농산물     339
화장품     264
시티웨어    213
Name: count, dtype: int64
24
주구매지점
본  점    1077
잠실점      474
분당점      436
부산본점     245
영등포점     241
Name: count, dtype: int64

In [171]:
# 필요한 라이브러리 불러오기
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [172]:
# 범주형 변수 인코딩 (LabelEncoder 사용)
le = LabelEncoder()

for col in cat_cols:
    X[col] = le.fit_transform(X[col])
    print(f"{col} 인코딩 완료")

X.head()

주구매상품 인코딩 완료
주구매지점 인코딩 완료

       총구매액     최대구매액       환불금액  주구매상품  주구매지점  내점일수   내점당구매건수    주말방문비율  구매주기
0  68282840  11264000  6860000.0      5      0    19  3.894737  0.527027    17
1   2136000   2136000   300000.0     21     19     2  1.500000  0.000000     1
2   3197000   1639000        0.0      6      1     2  2.000000  0.000000     1
3  16077620   4935000        0.0      5      2    18  2.444444  0.318182    16
4  29050000  24000000        0.0     15      8     2  1.500000  0.000000    85

In [173]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [174]:
scaler = StandardScaler() #클래스 > import
X_scaled = scaler.fit_transform(X)
# X_scaled[:3]
X_scaled #numpy의 array

array([[-0.14458009, -0.26260786, -0.04750476, ...,  0.55424743,
         0.75862274, -0.15996211],
       [-0.54918957, -0.54796686, -0.26546133, ..., -0.69816782,
        -1.06053002, -0.80655356],
       [-0.5426996 , -0.56350404, -0.27542885, ..., -0.43667453,
        -1.06053002, -0.80655356],
       ...,
       [-0.56179637, -0.61239772, -0.27542885, ..., -0.95966112,
        -1.06053002, -0.84696552],
       [-0.55078606, -0.58348042, -0.27542885, ..., -0.95966112,
        -1.06053002,  0.72910114],
       [ 1.04709431,  0.46792117, -0.07697541, ..., -0.21646965,
         0.55277658, -0.5236698 ]], shape=(3500, 9))

In [175]:

# 학습/테스트 데이터 분리 (8:2 비율)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42,
    stratify=y #y가 불균형이므로 설정
)
X_train.shape, X_test.shape

((2800, 9), (700, 9))

In [176]:
from sklearn.linear_model import LogisticRegression

In [177]:
X_train, X_test, y_train, y_test

(array([[ 0.08226136,  0.16680616, -0.27542885, ..., -0.54127184,
          1.70085057, -0.32160997],
        [-0.553924  , -0.58191732, -0.27542885, ..., -0.95966112,
          0.66533285,  1.77981225],
        [-0.49402456, -0.36073909, -0.27542885, ..., -0.43667453,
          0.23386713,  1.49692849],
        ...,
        [-0.5511921 , -0.58660662, -0.27542885, ...,  1.39377854,
          1.13602273,  2.79011139],
        [ 0.67521934, -0.2658591 , -0.26778708, ...,  1.8232033 ,
          0.05664682, -0.72572963],
        [ 4.5535857 ,  1.60485543,  0.44223302, ...,  0.04344431,
          0.21932335, -0.6449057 ]], shape=(2800, 9)),
 array([[-0.55522077, -0.57879113, -0.27542885, ..., -0.95966112,
          2.39119572, -0.84696552],
        [-0.52677136, -0.46624814, -0.21402889, ..., -0.78533225,
          1.52826429, -0.60449373],
        [-0.53922524, -0.54665386, -0.27542885, ..., -0.69816782,
         -1.06053002, -0.36202194],
        ...,
        [ 0.09294307,  0.26609408,  0.47074015, ...,  1.50145225,
          0.18493803, -0.07913818],
        [-0.49681476, -0.4114147 , -0.27542885, ..., -0.22747989,
         -0.77288621,  1.45651652],
        [-0.20597412,  1.03588811, -0.02105759, ..., -0.50204785,
          1.24062048,  0.890749  ]], shape=(700, 9)),
 3316    1
 2726    1
 3012    1
 2415    1
 2803    1
        ..
 1164    0
 2281    1
 2352    1
 2394    0
 301     0
 Name: gender, Length: 2800, dtype: int64,
 2398    1
 3321    0
 1277    1
 2053    1
 3025    0
        ..
 102     1
 3274    1
 2793    0
 3100    0
 2305    0
 Name: gender, Length: 700, dtype: int64)

In [178]:
lr_model = LogisticRegression(random_state=42, max_iter=1000, class_weight="balanced")

In [179]:
lr_model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [180]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [181]:
# 예측
lr_pred = lr_model.predict(X_test)

In [182]:
def evaluate_classifier(y_true, y_pred):
    # 정확도: 전체 정답 비율
    acc = accuracy_score(y_true, y_pred)

    # 정밀도/재현율/F1: 기본적으로 positive label = 1 기준
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    # 혼동행렬: [[TN, FP], [FN, TP]]
    cm = confusion_matrix(y_true, y_pred)

    print("Accuracy :", round(acc, 4))
    print("Precision:", round(prec, 4))
    print("Recall   :", round(rec, 4))
    print("F1       :", round(f1, 4))
    print("\nConfusion Matrix")
    print(cm)

In [183]:
evaluate_classifier(y_test, lr_pred)

Accuracy : 0.55
Precision: 0.4333
Recall   : 0.6426
F1       : 0.5176

Confusion Matrix
[[216 221]
 [ 94 169]]

In [184]:
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred=dt_model.predict(X_test)
evaluate_classifier(y_test, dt_pred)

Accuracy : 0.5657
Precision: 0.4232
Recall   : 0.4297
F1       : 0.4264

Confusion Matrix
[[283 154]
 [150 113]]

In [185]:
dt_model

DecisionTreeClassifier(random_state=42)

In [186]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(random_state=42, n_estimators=100)
rf_model.fit(X_train, y_train)
rf_pred=rf_model.predict(X_test)
evaluate_classifier(y_test, rf_pred)

Accuracy : 0.6286
Precision: 0.5087
Recall   : 0.3346
F1       : 0.4037

Confusion Matrix
[[352  85]
 [175  88]]

In [189]:
rf_model_1=RandomForestClassifier(
  random_state=42,
  n_estimators=300,
  max_depth=10,
  min_samples_leaf=5,
  class_weight="balanced"
)
rf_model_1.fit(X_train, y_train)
rf_pred_1=rf_model_1.predict(X_test)
evaluate_classifier(y_test, rf_pred_1)

Accuracy : 0.61
Precision: 0.4828
Recall   : 0.5323
F1       : 0.5063

Confusion Matrix
[[287 150]
 [123 140]]

In [190]:
from xgboost import XGBClassifier
xgb_model=XGBClassifier(
  random_state=42,
  n_estimators=100,
  eval_metric='logloss'
)
xgb_model.fit(X_train, y_train)
xgb_pred=xgb_model.predict(X_test)
evaluate_classifier(y_test, xgb_pred)

Accuracy : 0.6371
Precision: 0.5207
Recall   : 0.4297
F1       : 0.4708

Confusion Matrix
[[333 104]
 [150 113]]

In [194]:
xgb_w=XGBClassifier(
  random_state=42,
  n_estimators=300,
  learn_rate=0.05,
  max_depth=4,
  subsample=0.8,
  colsample_bytree=0.8,
  eval_metric='logloss',
  scale_pos_weight=1.66
)
xgb_w.fit(X_train, y_train)
pred_xgb_w=xgb_w.predict(X_test)
evaluate_classifier(y_test, pred_xgb_w)

Accuracy : 0.6214
Precision: 0.4962
Recall   : 0.4981
F1       : 0.4972

Confusion Matrix
[[304 133]
 [132 131]]

In [195]:
proba = xgb_w.predict_proba(X_test)[:, 1]
proba

array([7.10092425e-01, 3.20365280e-01, 3.64352167e-01, 9.96106088e-01,
       1.78763703e-01, 4.54514056e-01, 5.39461374e-02, 8.09052214e-02,
       9.75403428e-01, 2.60185272e-01, 8.99281632e-03, 8.73750269e-01,
       7.34530985e-01, 1.59676224e-01, 9.48481977e-01, 4.98013198e-01,
       8.57741475e-01, 5.02201021e-01, 2.09305763e-01, 6.11862242e-01,
       7.82562494e-01, 7.12513506e-01, 3.64646971e-01, 4.68580663e-01,
       4.24549490e-01, 1.45637468e-02, 6.19229674e-01, 1.53841987e-01,
       9.50372577e-01, 6.07357740e-01, 3.94206315e-01, 2.15962976e-02,
       9.96474683e-01, 1.83320977e-02, 4.61601794e-01, 9.85186040e-01,
       3.24730903e-01, 7.98710704e-01, 1.81106374e-01, 7.03984797e-01,
       4.24616069e-01, 3.60787511e-02, 5.09446952e-03, 6.64911449e-01,
       8.35388675e-02, 5.96825108e-02, 2.13602334e-01, 2.80473214e-02,
       1.04310989e-01, 7.16624677e-01, 4.81357247e-01, 1.56125024e-01,
       8.83009136e-01, 2.51135111e-01, 9.05402660e-01, 6.04649305e-01,
       9.36301827e-01, 7.24488753e-04, 3.26087624e-01, 5.67283109e-02,
       1.84455335e-01, 4.67124619e-02, 6.82611108e-01, 3.73295814e-01,
       1.41503394e-01, 2.93074638e-01, 8.85314774e-03, 9.44449902e-01,
       6.99659958e-02, 4.25292641e-01, 5.84837198e-01, 1.63429484e-01,
       3.27113301e-01, 7.08941042e-01, 3.52765292e-01, 4.42750901e-01,
       5.79379141e-01, 2.93605831e-02, 4.06275362e-01, 8.73196185e-01,
       7.60112166e-01, 8.69766623e-03, 3.76690954e-01, 9.18856934e-02,
       4.69380260e-01, 7.91635454e-01, 5.89387901e-02, 2.03568846e-01,
       2.25657612e-01, 6.78154469e-01, 5.10984659e-01, 2.47393325e-02,
       6.48481250e-01, 2.18295664e-01, 5.79131842e-02, 9.09538507e-01,
       3.25211257e-01, 4.42050755e-01, 3.25840741e-01, 1.43731907e-01,
       1.42839119e-01, 9.31821227e-01, 8.43165755e-01, 5.29866926e-02,
       9.63766575e-01, 4.10157479e-02, 4.02311623e-01, 1.98513657e-01,
       7.07374036e-01, 6.90193415e-01, 3.00725490e-01, 2.37559993e-03,
       1.70752376e-01, 2.77149230e-01, 5.53471744e-01, 9.57313031e-02,
       8.97576213e-02, 7.99194071e-03, 4.79129881e-01, 1.67319346e-02,
       1.31241363e-02, 6.69755340e-01, 1.13862857e-01, 6.26839578e-01,
       1.54749587e-01, 8.12607706e-01, 1.35256955e-02, 4.69345540e-01,
       2.88069338e-01, 3.04637551e-01, 1.13417402e-01, 5.38352311e-01,
       4.18198317e-01, 4.32976335e-01, 2.47612640e-01, 8.62066329e-01,
       2.91626751e-01, 5.55423617e-01, 2.38490775e-01, 2.51095835e-02,
       5.87285459e-01, 6.44628942e-01, 4.57361490e-01, 2.26472437e-01,
       5.11857331e-01, 6.66158438e-01, 1.21469416e-01, 2.53136475e-02,
       7.69052088e-01, 9.59041238e-01, 7.72713497e-02, 5.20450532e-01,
       2.25413546e-01, 1.99056063e-02, 6.66804790e-01, 6.94035888e-01,
       2.57917285e-01, 2.05401957e-01, 1.60168782e-01, 8.96457374e-01,
       9.55406010e-01, 3.23857725e-01, 2.37355307e-02, 9.79223847e-01,
       2.97833513e-02, 7.41842464e-02, 6.75554514e-01, 9.92063820e-01,
       3.30041647e-01, 2.53847063e-01, 3.26139241e-01, 1.89198907e-02,
       9.72760856e-01, 1.57056395e-02, 5.72166383e-01, 2.17591561e-02,
       5.63610971e-01, 7.06864119e-01, 1.49500191e-01, 5.18601418e-01,
       8.09059963e-02, 6.09617114e-01, 7.80759037e-01, 9.18621302e-01,
       8.82239118e-02, 6.83682919e-01, 1.80519357e-01, 1.38137549e-01,
       7.56485522e-01, 9.87382114e-01, 3.96746427e-01, 7.55975962e-01,
       2.15425789e-01, 1.02948479e-01, 7.07561851e-01, 1.52788967e-01,
       4.07680154e-01, 5.02055645e-01, 4.98762101e-01, 4.77096587e-01,
       7.51296759e-01, 2.38594756e-01, 7.96201676e-02, 1.74294055e-01,
       8.20075035e-01, 3.82352889e-01, 3.10678352e-02, 6.15502477e-01,
       3.48338522e-02, 2.25800261e-01, 5.86260259e-01, 1.60381645e-01,
       2.24657848e-01, 1.54584020e-01, 7.90836990e-01, 3.12966883e-01,
       8.50795865e-01, 7.43288755e-01, 1.58354878e-01, 8.93380046e-01,
       5.11857331e-01, 1.56626523e-01, 8.06779206e-01, 4.87012476e-01,
       3.16055492e-04, 8.24753344e-02, 1.05906218e-01, 7.11661339e-01,
       7.88937747e-01, 7.37531304e-01, 8.25773597e-01, 6.66849077e-01,
       9.34506178e-01, 2.20803738e-01, 9.90614071e-02, 1.99211776e-01,
       3.69120389e-01, 8.39427114e-02, 7.94596434e-01, 9.38760281e-01,
       9.39520895e-01, 4.50303525e-01, 8.72679472e-01, 2.14107595e-02,
       4.05472040e-01, 8.58685017e-01, 1.82838812e-01, 9.19410214e-02,
       6.08026981e-01, 3.10623258e-01, 1.30950110e-02, 8.47947061e-01,
       3.75058651e-02, 8.64424743e-03, 6.08669519e-01, 2.81539392e-02,
       4.14846510e-01, 8.18848550e-01, 9.71521512e-02, 9.26507935e-02,
       4.26918894e-01, 7.77906775e-01, 6.47691727e-01, 2.78974593e-01,
       8.27589989e-01, 6.02518953e-02, 3.04540336e-01, 9.37687516e-01,
       6.72074616e-01, 9.43408906e-01, 1.65939797e-02, 7.66136050e-01,
       2.36559823e-01, 2.95075849e-02, 6.80494159e-02, 5.11010826e-01,
       6.76256344e-02, 1.85769200e-01, 1.55536681e-01, 8.78134668e-01,
       4.69617158e-01, 6.84890807e-01, 9.38670576e-01, 2.13519633e-02,
       5.91994345e-01, 6.10279262e-01, 9.28224087e-01, 1.19011523e-02,
       8.68448755e-04, 6.17460668e-01, 5.97590983e-01, 1.09209739e-01,
       3.49882036e-01, 2.38862172e-01, 4.52194571e-01, 2.41691321e-01,
       4.73006099e-01, 6.44246817e-01, 9.31708097e-01, 5.45207690e-03,
       3.97271337e-03, 1.04167201e-01, 2.09901825e-01, 3.30243081e-01,
       3.42537671e-01, 6.00755811e-02, 9.21954334e-01, 5.40007770e-01,
       2.55541086e-01, 9.72670019e-01, 7.51668215e-01, 5.95123470e-01,
       1.25360519e-01, 3.43550235e-01, 4.35664654e-01, 7.76415542e-02,
       9.04402375e-01, 6.10148311e-02, 7.95314491e-01, 1.61393225e-01,
       5.56120500e-02, 1.22545242e-01, 1.18414566e-01, 1.88731238e-01,
       3.50566171e-02, 6.79480016e-01, 3.65234941e-01, 8.57356727e-01,
       9.85308230e-01, 7.95297503e-01, 1.34818017e-01, 9.51110721e-01,
       1.98713958e-01, 4.40094799e-01, 3.16660553e-02, 5.95649898e-01,
       3.19227517e-01, 2.99659729e-01, 1.14265375e-01, 5.63972175e-01,
       6.28362775e-01, 5.46754003e-01, 1.67178228e-01, 6.52117670e-01,
       2.04125568e-02, 2.85426438e-01, 4.49876815e-01, 6.35494232e-01,
       5.47360480e-01, 8.80430045e-04, 1.83434188e-02, 6.50434554e-01,
       5.95682502e-01, 8.39401305e-01, 6.47794843e-01, 7.56012261e-01,
       9.02895629e-01, 2.82954779e-02, 9.79925469e-02, 6.39657021e-01,
       8.33309963e-02, 7.27474749e-01, 5.14716566e-01, 8.20505857e-01,
       5.97895086e-01, 8.04017484e-03, 2.32343376e-01, 5.27781069e-01,
       5.84571958e-01, 8.92391086e-01, 5.59680879e-01, 1.46326303e-01,
       6.86928183e-02, 6.54857606e-02, 3.55921611e-02, 5.75601757e-02,
       1.80420369e-01, 4.47712094e-01, 2.32591331e-01, 2.42755368e-01,
       2.38200292e-01, 2.28390485e-01, 3.36755902e-01, 1.44095659e-01,
       5.58388948e-01, 1.03512742e-01, 9.26474452e-01, 1.71044052e-01,
       1.45837635e-01, 1.38101757e-01, 1.60321712e-01, 9.22630504e-02,
       9.51041877e-01, 3.07419509e-01, 4.17262726e-02, 2.76230633e-01,
       5.98265767e-01, 6.53975755e-02, 3.44189256e-01, 2.96109319e-01,
       4.21154387e-02, 1.04241125e-01, 5.44704139e-01, 1.23273708e-01,
       7.08364189e-01, 2.10618019e-01, 9.59434211e-02, 3.77374212e-03,
       5.57533681e-01, 3.37955177e-01, 1.21061288e-01, 3.62750828e-01,
       8.48203957e-01, 8.16806704e-02, 9.22272325e-01, 1.83580726e-01,
       9.00875270e-01, 1.70365885e-01, 1.69706792e-01, 3.29726458e-01,
       4.36847866e-01, 9.22462761e-01, 5.88612974e-01, 8.14035833e-02,
       8.41536403e-01, 2.88188040e-01, 6.74637556e-01, 5.53374708e-01,
       2.47326747e-01, 4.72436130e-01, 4.13176566e-01, 1.02630258e-01,
       1.98340788e-01, 2.47769699e-01, 3.73145252e-01, 1.16293326e-01,
       9.19299480e-03, 8.13131630e-01, 6.85858548e-01, 7.19364464e-01,
       9.97576177e-01, 2.97838092e-01, 9.32223976e-01, 5.98402636e-04,
       8.84109318e-01, 1.39105013e-02, 9.04154480e-01, 3.80134523e-01,
       6.67760968e-02, 7.93542266e-01, 3.29067975e-01, 4.35823113e-01,
       2.91165590e-01, 3.88503939e-01, 6.40616477e-01, 1.25970960e-01,
       3.92080069e-01, 9.75279272e-01, 1.21124305e-01, 4.84348506e-01,
       4.41442221e-01, 2.03289818e-02, 9.62303758e-01, 3.21109414e-01,
       4.51819301e-01, 1.18595183e-01, 1.19148739e-01, 2.35948369e-01,
       5.17573655e-01, 2.86589861e-01, 1.47948219e-02, 8.62983704e-01,
       3.15255731e-01, 8.10550079e-02, 2.70146728e-02, 9.48193669e-01,
       6.46041259e-02, 1.81978792e-01, 1.71864182e-01, 1.78986359e-02,
       8.66605818e-01, 2.42139250e-01, 8.45906258e-01, 7.87422210e-02,
       9.21534240e-01, 2.04067469e-01, 4.81645837e-02, 4.77111012e-01,
       2.60919575e-02, 1.91098720e-01, 7.85219491e-01, 1.74565315e-01,
       5.80209434e-01, 7.66566873e-01, 8.15960526e-01, 5.69234908e-01,
       5.55426776e-01, 2.41150767e-01, 2.65209466e-01, 6.87225401e-01,
       4.13766988e-02, 9.03399646e-01, 4.21243086e-02, 6.13555253e-01,
       2.97362339e-02, 5.07243037e-01, 2.07077358e-02, 1.16100468e-01,
       8.13324749e-02, 3.11696138e-02, 8.41689944e-01, 6.01785593e-02,
       1.27536148e-01, 1.23126261e-01, 6.18667781e-01, 4.18621711e-02,
       7.64319837e-01, 2.09508106e-01, 9.85574603e-01, 6.01583421e-02,
       6.16008155e-02, 1.78100064e-01, 4.61706251e-01, 2.13435546e-01,
       5.99338830e-01, 9.27107632e-01, 6.18717074e-01, 6.48603559e-01,
       7.97534734e-02, 1.24370545e-01, 4.06565845e-01, 5.69935977e-01,
       3.53704989e-02, 5.86181045e-01, 8.41822126e-04, 1.39150470e-01,
       9.33247805e-01, 7.93402612e-01, 3.79660308e-01, 4.19419892e-02,
       6.84315622e-01, 1.19830333e-02, 9.36232328e-01, 9.74682868e-01,
       8.10669065e-02, 3.90912473e-01, 5.98032355e-01, 8.05413842e-01,
       6.37425125e-01, 2.23121688e-01, 6.75761849e-02, 7.36865923e-02,
       8.23578179e-01, 8.31491232e-01, 2.12744683e-01, 4.71232682e-01,
       7.67590225e-01, 7.23295093e-01, 1.11985214e-01, 5.09716034e-01,
       6.03269756e-01, 8.33764300e-02, 2.14869063e-02, 4.64908808e-01,
       5.03853261e-01, 4.93247449e-01, 1.03362016e-01, 9.42060530e-01,
       5.39049327e-01, 7.63571978e-01, 1.27377445e-02, 4.11301911e-01,
       1.78688765e-01, 6.48381412e-01, 6.96069654e-03, 9.47510839e-01,
       8.48712683e-01, 1.46868499e-02, 2.97585964e-01, 4.79656495e-02,
       1.81402639e-02, 5.58555961e-01, 9.84766006e-01, 6.95924222e-01,
       1.71119437e-01, 6.41148925e-01, 8.01138043e-01, 5.92237175e-01,
       3.34073961e-01, 9.00132000e-01, 9.94753122e-01, 1.12096190e-01,
       9.91454363e-01, 6.59865260e-01, 4.73932862e-01, 4.91921306e-01,
       1.74775422e-01, 1.77482367e-01, 1.47100776e-01, 2.99056679e-01,
       8.72672141e-01, 2.89451957e-01, 8.40143621e-01, 2.91315585e-01,
       8.81778657e-01, 7.58328378e-01, 7.73449019e-02, 2.65611023e-01,
       5.60390174e-01, 3.63147050e-01, 9.21690464e-03, 1.18597902e-01,
       3.03730398e-01, 9.35387254e-01, 9.95800178e-03, 8.04878533e-01,
       1.53305963e-01, 3.67339522e-01, 4.25591677e-01, 2.80234427e-03,
       3.79692942e-01, 9.71838892e-01, 5.38301282e-02, 8.91495943e-01,
       1.98244397e-02, 2.25866258e-01, 9.53482449e-01, 3.20956036e-02,
       3.61640841e-01, 2.46271435e-02, 1.47940516e-01, 1.37111932e-01,
       5.21923937e-02, 7.45697394e-02, 9.19299424e-01, 3.13465595e-02,
       3.48708034e-01, 5.29657565e-02, 4.19730544e-01, 4.03086066e-01,
       9.94577527e-01, 8.06599975e-01, 2.79641569e-01, 1.35896444e-01,
       6.68658257e-01, 9.04605925e-01, 1.02683231e-01, 5.70231751e-02,
       1.10330964e-02, 4.01222631e-02, 2.70252638e-02, 9.36991572e-01,
       4.44226265e-01, 7.14331865e-01, 6.34016236e-03, 3.92115116e-02,
       2.07158893e-01, 1.41998738e-01, 6.89166188e-02, 8.53757560e-01,
       1.73207745e-01, 2.16459066e-01, 3.15954983e-01, 4.02602851e-02,
       1.41277313e-01, 4.78772432e-01, 3.36950482e-03, 9.20209706e-01,
       8.19545821e-04, 4.54767287e-01, 7.12313354e-01, 2.38018990e-01,
       9.57130432e-01, 4.98579621e-01, 5.67952991e-01, 4.24043089e-01,
       1.09392844e-01, 1.26484320e-01, 3.44641715e-01, 8.44891191e-01,
       2.05338567e-01, 5.94409049e-01, 1.10608255e-02, 1.40908033e-01,
       8.34679782e-01, 1.30652755e-01, 2.81715810e-01, 4.07580733e-01,
       3.76706064e-01, 9.83769119e-01, 5.24742119e-02, 3.53735825e-03,
       2.95643806e-01, 1.98320061e-01, 9.60981250e-01, 8.18729579e-01,
       1.70705825e-01, 4.28968161e-01, 4.78768110e-01, 4.30521041e-01],
      dtype=float32)

In [196]:
rows = []
for thr in [0.35, 0.40, 0.45, 0.50, 0.55, 0.60]: #임계값에 따라 0/1 인지 판정만 다시한다.
    pred_thr = (proba >= thr).astype(int)

    rows.append({
        "threshold": thr,
        "accuracy": round(accuracy_score(y_test, pred_thr), 4),
        "precision": round(precision_score(y_test, pred_thr), 4),
        "recall": round(recall_score(y_test, pred_thr), 4),
        "f1": round(f1_score(y_test, pred_thr), 4)
    })

thr_result = pd.DataFrame(rows)
display(thr_result)

best_thr = float(thr_result.sort_values("f1", ascending=False).iloc[0]["threshold"])
best_pred = (proba >= best_thr).astype(int)

print("F1 기준 best threshold:", best_thr)
print("Confusion Matrix\n", confusion_matrix(y_test, best_pred))

   threshold  accuracy  precision  recall      f1
0       0.35    0.5914     0.4669  0.6160  0.5311
1       0.40    0.6029     0.4769  0.5894  0.5272
2       0.45    0.6043     0.4762  0.5323  0.5027
3       0.50    0.6214     0.4962  0.4981  0.4972
4       0.55    0.6243     0.5000  0.4639  0.4813
5       0.60    0.6271     0.5048  0.4030  0.4482

F1 기준 best threshold: 0.35
Confusion Matrix
 [[252 185]
 [101 162]]

In [197]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [198]:
# 1. 테스트해볼 파라미터들을 딕셔너리 형태로 정합니다.
param_grid = {
    'n_estimators': [100, 200],       # 나무의 개수
    'max_depth': [None, 10, 20],      # 나무의 최대 깊이 (너무 깊으면 과적합 위험)
    'min_samples_split': [2, 5, 10],  # 노드를 나누기 위한 최소 샘플 수
    'min_samples_leaf': [1, 2, 4]     # 리프 노드가 되기 위한 최소 샘플 수
}

# 2. 랜덤 포레스트 모델 생성
rf = RandomForestClassifier(random_state=42)

# 3. GridSearchCV 설정
# scoring='f1'을 써서 F1-Score가 가장 높은 조합을 찾도록 합니다.
# cv=5는 데이터를 5등분해서 교차 검증을 하겠다는 뜻입니다.
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, 
                           cv=5, scoring='f1', n_jobs=-1)

# 4. 학습 시작 (컴퓨터가 열심히 조합을 맞춰봅니다)
grid_search.fit(X_train, y_train)

# 5. 최적의 파라미터와 최고 점수 확인
print(f"최적 파라미터: {grid_search.best_params_}")
print(f"최고 F1 Score: {grid_search.best_score_:.4f}")

# 6. 최적의 모델로 예측하기
best_rf = grid_search.best_estimator_
rf_pred = best_rf.predict(X_test)

# 평가 함수 호출 (사용하시던 evaluate_classifier 함수)
evaluate_classifier(y_test, rf_pred)

최적 파라미터: {'max_depth': 20, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 200}
최고 F1 Score: 0.4295
Accuracy : 0.64
Precision: 0.5333
Recall   : 0.3346
F1       : 0.4112

Confusion Matrix
[[360  77]
 [175  88]]

In [199]:
from sklearn.ensemble import RandomForestClassifier

# 1. GridSearchCV로 찾은 최적 파라미터에 class_weight만 추가합니다.
rf_balanced = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    min_samples_leaf=4,
    min_samples_split=2,
    random_state=42,
    class_weight='balanced'  # <--- 핵심! 부족한 클래스에 가중치를 자동으로 부여
)

# 2. 모델 학습
rf_balanced.fit(X_train, y_train)

# 3. 예측
rf_pred_balanced = rf_balanced.predict(X_test)

# 4. 결과 확인 (사용하시던 evaluate_classifier 함수)
evaluate_classifier(y_test, rf_pred_balanced)

Accuracy : 0.6357
Precision: 0.5168
Recall   : 0.4677
F1       : 0.491

Confusion Matrix
[[322 115]
 [140 123]]